# Generated by Django 2.0.4 on 2018-08-27 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Provider', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassengerTB',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=250)),
                ('SecondName', models.CharField(max_length=250)),
                ('PassportNo', models.CharField(max_length=250)),
                ('PassengerType', models.CharField(max_length=10)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=18)),
            ],
        ),
        migrations.CreateModel(
            name='PNRTB',
            fields=[
                ('ID', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('BookingType', models.IntegerField()),
                ('Total', models.DecimalField(decimal_places=2, max_digits=18)),
                ('PassenagerNo', models.IntegerField()),
                ('BookingURL', models.CharField(max_length=250)),
                ('BlockSeat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Provider.BlockSeatTB')),
                ('Client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Provider.ProviderClientTB')),
                ('ClientOffer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Provider.ClientOfferTB')),
                ('Credit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Provider.ClientCreditTB')),
                ('Tproduct', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Provider.TProductTB')),
            ],
        ),
        migrations.AddField(
            model_name='passengertb',
            name='PNR',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Client.PNRTB'),
        ),
    ]
