# Generated by Django 2.0.4 on 2018-08-26 21:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArrCountryTB',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('CountrySymbol', models.CharField(max_length=5)),
                ('CountryName', models.CharField(max_length=250)),
                ('StateName', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='ClientTB',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Client', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DepCountryTB',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('CountrySymbol', models.CharField(max_length=5)),
                ('CountryName', models.CharField(max_length=250)),
                ('StateName', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='ProviderTB',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Provider', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
