# Generated by Django 2.0.4 on 2018-09-01 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topex', '0002_airlinetb_servicetb'),
    ]

    operations = [
        migrations.AddField(
            model_name='providertb',
            name='license',
            field=models.CharField(default='empty', max_length=250),
        ),
    ]
