# Generated by Django 2.0.4 on 2018-09-04 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topex', '0004_userinfotb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfotb',
            old_name='UserID',
            new_name='User',
        ),
    ]
