# Generated by Django 2.0.4 on 2018-09-04 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topex', '0005_auto_20180904_0951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='providertb',
            name='license',
        ),
    ]
