# Generated by Django 2.0.4 on 2018-09-13 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topex', '0007_userinfotb_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfotb',
            name='Mobile',
            field=models.CharField(default='07821070993', max_length=20),
        ),
    ]
