# Generated by Django 2.0.4 on 2018-09-21 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topex', '0011_auto_20180921_0245'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfotb',
            name='license_pdf',
            field=models.FileField(null=True, upload_to='licenseDoc'),
        ),
    ]
