# Generated by Django 2.0.4 on 2018-09-22 00:00

from django.db import migrations, models
import topex.models


class Migration(migrations.Migration):

    dependencies = [
        ('topex', '0012_userinfotb_license_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfotb',
            name='license_pdf',
        ),
        migrations.AlterField(
            model_name='userinfotb',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to=topex.models.PathAndRename('Logo')),
        ),
    ]
