# Generated by Django 2.0.4 on 2018-09-26 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topex', '0014_userinfotb_license_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfotb',
            name='TheEmail',
            field=models.EmailField(default=2, max_length=254),
            preserve_default=False,
        ),
    ]
