# Generated by Django 2.0.4 on 2018-10-08 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Provider', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerclienttb',
            name='ConfirmationFlag',
            field=models.BooleanField(default=False),
        ),
    ]
