# Generated by Django 2.0.4 on 2018-10-25 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topex', '0015_userinfotb_theemail'),
        ('Provider', '0003_auto_20181009_1702'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='providerclienttb',
            unique_together={('Client', 'Provider')},
        ),
    ]
