# Generated by Django 2.0.4 on 2018-07-16 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0003_track'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='owner',
            field=models.CharField(default='hakim', max_length=100),
        ),
    ]
